### ISSUE TITLE
Link is down :(

### ISSUE THREAD

**Issue by Mennaruuk** [alexandrus21a/Youtubify#1]
**Describe the bug**
https://alexandrus21a.vercel.app/youtubedl.html is down

**To Reproduce**
1. Go to https://alexandrus21a.vercel.app/youtubedl.html
2. Check site for 404 error

**Expected behavior**
Site should be up! Seems like a good tool

**Screenshots**
![Screenshot_2021-02-06 404 NOT_FOUND_censored](https://user-images.githubusercontent.com/52135169/107128138-42798300-6889-11eb-9522-a0d711003831.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 85.0.1

**Additional context**
None

**Comment by alexandrus21a** [comment]
thanks for the feedback, the page is in development, and rushing to the best of my ability

**Comment by Mennaruuk** [comment]
Take your time!! No need to rush, please. Just wanted to bring this to your attention. Thanks for your assistance!
